#pragma once
#ifndef CONFIG_H
#define CONFIG_H

/*
    Input-to-key mappings
    
    For each input, both normal and shifted mappings are defined. 0 means no mapping.
    
    Holding P1 Start will cause the shifted mapping of an input to be used.
    (The exception is P1 Start, which has no shifted meaning.)
*/

#define MAPPING_P1_UP       HID_KEYBOARD_UP_ARROW, HID_KEYBOARD_TAB
#define MAPPING_P1_DOWN     HID_KEYBOARD_DOWN_ARROW, HID_KEYBOARD_F2
#define MAPPING_P1_LEFT     HID_KEYBOARD_LEFT_ARROW, HID_KEYBOARD_ESCAPE
#define MAPPING_P1_RIGHT    HID_KEYBOARD_RIGHT_ARROW, HID_KEYBOARD_ENTER
#define MAPPING_P1_BUTTON1  HID_KEYBOARD_LEFT_CONTROL, HID_KEYBOARD_5_AND_PERCENT
#define MAPPING_P1_BUTTON2  HID_KEYBOARD_LEFT_ALT, 0
#define MAPPING_P1_BUTTON3  HID_KEYBOARD_SPACEBAR, 0
#define MAPPING_P1_BUTTON4  HID_KEYBOARD_LEFT_SHIFT, 0
#define MAPPING_P1_BUTTON5  HID_KEYBOARD_Z_AND_Z, 0
#define MAPPING_P1_BUTTON6  HID_KEYBOARD_X_AND_X, 0
#define MAPPING_P1_START    HID_KEYBOARD_1_AND_EXCLAMATION_POINT, 0
#define MAPPING_P1_COIN     HID_KEYBOARD_5_AND_PERCENT, 0

#define MAPPING_P2_UP       HID_KEYBOARD_R_AND_R, 0
#define MAPPING_P2_DOWN     HID_KEYBOARD_F_AND_F, 0
#define MAPPING_P2_LEFT     HID_KEYBOARD_D_AND_D, 0
#define MAPPING_P2_RIGHT    HID_KEYBOARD_G_AND_G, 0
#define MAPPING_P2_BUTTON1  HID_KEYBOARD_A_AND_A, 0
#define MAPPING_P2_BUTTON2  HID_KEYBOARD_S_AND_S, 0
#define MAPPING_P2_BUTTON3  HID_KEYBOARD_Q_AND_Q, 0
#define MAPPING_P2_BUTTON4  HID_KEYBOARD_W_AND_W, 0
#define MAPPING_P2_BUTTON5  HID_KEYBOARD_I_AND_I, 0
#define MAPPING_P2_BUTTON6  HID_KEYBOARD_K_AND_K, HID_KEYBOARD_F11
#define MAPPING_P2_START    HID_KEYBOARD_2_AND_AT, 0

#endif
